### ISSUE TITLE
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['protocols', 'bgp', 'nsr', 'enable']]

### ISSUE THREAD

**Issue by Olichous** [CiscoTestAutomation/genielibs#42] opened 2021-02-02 10:39 UTC
Hi Guys,

Trying to use the genie learn('ospf') function on a iosxr equipement.
The output start and close with this error :

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "src/genie/conf/base/device.py", line 626, in genie.conf.base.device.Device.learn
  File "/home/admin/pyATS/lib/python3.6/site-packages/genie/libs/ops/ospf/iosxr/ospf.py", line 1015, in learn
    self.make(final_call=True)
  File "/home/admin/pyATS/lib/python3.6/site-packages/genie/ops/base/base.py", line 101, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 312, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 418, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['protocols', 'bgp', 'nsr', 'enable']]

The router running Version 5.1.3 IOSXR.

Thanks for your help ;-)

Olivier.

**Comment by xiaoxinz-cisco** [comment] 2021-02-02 15:16
Hi Olivier(@Olichous ),

It looks like the parser doesn't work properly. Do you mind sharing with us the outputs of show commands? 

Thanks

**Comment by Olichous** [comment] 2021-02-05 10:37
Hi Xiaoxinz, 

Thanks for you reply.
I do not have the next command so i

The last command is : "show protocols afi-all all"

The output is complete and after i have that :

RP/0/RSP1/CPU0:GSC-WASR9K-REC-HDI#
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "src/genie/conf/base/device.py", line 626, in genie.conf.base.device.Device.learn
  File "/home/admin/pyATS/lib/python3.6/site-packages/genie/libs/ops/ospf/iosxr/ospf.py", line 1015, in learn
    self.make(final_call=True)
  File "/home/admin/pyATS/lib/python3.6/site-packages/genie/ops/base/base.py", line 101, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 312, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 418, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 303, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 404, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['protocols', 'bgp', 'nsr', 'enable']]

**Comment by badalsoyantar** [comment] 2021-02-09 15:48
Hi @Olichous Output of the show command might be different and need to be handled in parser code. 
The issue is in following line.
https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxr/show_protocol.py#L130
You can create a pull request here:
https://github.com/CiscoTestAutomation/genieparser/pulls

If you are not sure where to make changes, you can send your output: pyats-support-ext@cisco.com
and we can help you out.

How to save output in a folder:
`
pyats learn ospf --testbed-file testbed.yaml --devices uut --output output_folder
`
Please find more details here.
https://pubhub.devnetcloud.com/media/pyats-getting-started/docs/quickstart/learndevices.html

**Comment by tahigash** [comment] 2021-03-27 16:32
Hi @Olichous I'm closing this issue since no update for a while. Please feel free to reopen if you still have the issue.

**Closed by tahigash** 2021-03-27 16:32 UTC
